version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    env_file:
      - ./env/.env
    ports:
      - "5432:5432"
    volumes:
      - ./.database/data:/var/lib/postgresql/data
      - ./.database/initdb:/docker-entrypoint-initdb.d

volumes:
  db_data:
